### ISSUE TITLE
Electron Cash & TrustedCoin sig script error 16

### ISSUE THREAD

**Issue by Darknicks** [fyookball/electrum#139]
Hello, 

So I've been reading several threads/issues here that are experiencing the same problem as I am. 

However, the "fix" or "solution" that is usually given is: "Just use your recovery seed to make a new wallet without 2fa enabled". Well that's the problem. I still have access to the 2fa codes that gets generated every few seconds but I DO NOT have the recovery seed. So the only way I'll be able to get my 4+ BCC from Electron Cash is when this gets fixed. 

Everytime I try to send coins, I get the "16 mandatory-script-verify-flag" error. 

I've tried changing servers but with no luck. The odd part is that some servers actually let me "broadcast" the transaction and supposedly "succeed" but when I try using the TX ID to look for the transaction in a BCH Block Explorer, it shows as invalid and even when I change the server, the "unconfirmed" transactions disappears from the list.

Please I need your help with this. 
I've seen quite a few users that have the same issue: no seed and script sig error/error16.

I contacted TrustedCoins but they pretty much said 'you're out of luck. Here's their message: 

> Sorry, but Trustedcoin's development team currently does not have the bandwidth to support BCH and it's unclear if/when support will be added.  
> Therefore, the only recourse 2FA users have to access their BCH is recovery from seed ( as described here https://github.com/fyookball/electrum/issues/41#issuecomment-320099854 ) so if you have lost your seed, you are out of luck for the time being.

So you're my only hope... Help me with this please.
@fyookball @badmofo @Otaci 

Thanks in advance!

**Comment by kyuupichan** [comment]
There is nothing we can do.  Trustedcoin have the private key and have decided to ignore their responsibility to their customers.  If you lost your seed you are reliant on them.

**Comment by Darknicks** [comment]
Isn't there a way to modify the Electron Cash code so that the signature is BCC compatible? Or maybe modify the signature? Also, when I tried to export the private key that has my coins and restore it in a new wallet, it shows a totally different public key that doesn't have any coins.


P. S. Sorry for the stupid things I might say here, since I'm not a dev and I have no idea how this stuff works

**Comment by kyuupichan** [comment]
No, it is trustedcoin that do the signature!  If we could do it we'd have the private key.

**Comment by Darknicks** [comment]
Why closed?

**Comment by Danconnolly** [comment]
It is closed because there really is nothing we can do to help you. Only trustedcoin.com can help you.

The trustedcoin.com service uses transactions that need two signatures. You can generate one, and trustedcoin.com generates the other. If trustedcoin.com refuse to generate the second, which is happening in this case, then you are stuck. No-one else can generate these signatures.

**Comment by Otaci** [comment]
It is closed because there really is nothing we can do to help you. Only trustedcoin.com can help you.

The trustedcoin.com service uses transactions that need two  signatures. You can generate one, and trustedcoin.com generates the  other. If trustedcoin.com refuse to generate the second, which is  happening in this case, then you are stuck. No-one else can generate  these signatures.

**Comment by stralvm** [comment]
I have the same problem, why is it possible to still choose for two factor authenticator when they don't support it?

**Comment by Danconnolly** [comment]
This will be removed in the next version.

You may find some assistance in #41
