### ISSUE TITLE
Unable to send BCH/BCC from Electron Cash

### ISSUE THREAD

**Issue by SilverstrandBC** [fyookball/electrum#150]
Not able to send BCH that I recently swept up from my paper wallet.  Error received says "transaction rejected by network rules.  (16: mandatory script verify flag failed (Singature must use SIGHAS_FORKID)...  "  

Please advise

**Comment by BigGucciAlex** [comment]
Same issue here, have been trying for days! Have tried multiple "fixes" still stuck. Very aggravating

**Comment by SilverstrandBC** [comment]
yeah, not a great position to be in...  had no problem transferring BCH prior to Electron Cash...  hhmmm

**Comment by HostFat** [comment]
Are you using the last version?
Are you sure that you are connected to a Bitcoin Cash/ABC server?
Is your wallet a 2FA wallet?

**Comment by SilverstrandBC** [comment]
version 2.9.3, server:  bcc.arihanc.com, wallet is 2FA...


I can see that the sweep was successful; the correct balance is in my electron cash wallet, just not able to send it to a different address.  Is this common?


David Tunbridge
Victoria, British Columbia
[http://graphics.hotmail.com/emrose.gif][http://graphics.hotmail.com/emcocktl.gif][http://graphics.hotmail.com/emlove.gif]


________________________________

**Comment by HostFat** [comment]
https://github.com/fyookball/electrum/issues/41

**Comment by SilverstrandBC** [comment]
not able to get past the install phase after restoring from orig seed...  stuck at 'please wait' screen after selecting 'next'

**Comment by BigGucciAlex** [comment]
Same ^

Really need this fixed. Absolutely ridiculous

**Comment by DarkLordGMS** [comment]
I know how to fix this. PM on reddit https://www.reddit.com/user/DarkLord_GMS/

**Comment by BigGucciAlex** [comment]
^Super legit guy^ 


Messaged him and he walked me through the steps. I was finally able to get my $BCH transaction sent to an exchange. Had been struggling with this since the fork!

**Comment by SilverstrandBC** [comment]
if anyone knows of a solution, please post...

**Comment by SilverstrandBC** [comment]
Still unable to access this BCH.  The program is getting hung up after I enter the seed...




________________________________

**Comment by DarkLordGMS** [comment]
Hello everyone,

I will be posting the instructions to recover your Bitcoin Cash from your TrustedCoin 2FA Bitcoin wallet.

As you might already know, TrustedCoin decided to not support Bitcoin Cash. Therefore, if you had a 2FA Bitcoin wallet with them and you try to send Bitcoin Cash with that same wallet after the fork, then you'll see the "signature error" message.

I will be showing you how to recover your coins and dump TrustedCoin for good.
To be able to do this, you will need the following:

* [Electron Cash v2.9.3 that can be downloaded by clicking this link.](https://electroncash.org/downloads/2.9.3/win-linux/electron-cash-2.9.3.exe)

* [Electrum v2.9.3 that can be downloaded by clicking this link.](https://download.electrum.org/2.9.3/electrum-2.9.3.exe)

* Your TrustedCoin 2FA wallet 12 word recovery seed. If you don't have this, you cannot recover the funds under any circumstances

* Basic file management knowledge (copying/pasting and renaming files)

* Patience

If you have all that, let's get started...

1) Open Electrum, no that's not a typo. Open Electrum NOT Electron Cash

2) On the top left corner, click the File menu

3) Click New/Restore

4) [You will see this window](http://i.imgur.com/ePJTPxm.png)

5) Type a wallet name. Please use something easy to remember. In this example we will use "TrustedCoin" as the wallet name

6) Click Next

7) [You will see this window](http://i.imgur.com/MPhbTzK.png)

8) Select the second option: "Wallet with two-factor authentication" and click Next

9) Click Next again

10) You will see the TrustedCoin disclaimer. Click Next

11) [You will see this window](http://i.imgur.com/WnPF1jZ.png)

12) Select the second option: "I already have a seed" and click Next

13) Type your 12 word recovery seed and click Next

14) [You will see this window.](http://i.imgur.com/VvtwCRc.png)

15) This is very important. Select the second option: "Disable" and click Next

16) If you want to use a password, type it in this window and click Next. 

Note: A password is not necessary since you will be dumping this wallet soon (highly recommended)

17) [After a few seconds, Electrum will recover your wallet using your seed and then you'll see this window](http://i.imgur.com/8Kv3WHK.png)

18) Click "File" again and then click "Save copy"

19) Now in the next window, it will give you the option of saving a backup of the wallet. I recommend saving it to an easy to find location like the Desktop. Use the same wallet name you used on the step #5. In this case, "TrustedCoin" and click "Save".

20) You will see a message box confirming the location where you saved the wallet backup. Click OK and close Electrum

21) Open Electron Cash

22) On the top left corner, click File and then click Open

23) Look for the wallet backup file you saved on the step #19

24) [If you used a password to encrypt the wallet on the step #16, you will see this window. Type your password and click Next to open the wallet.](http://i.imgur.com/mzHtMDn.png)

Note: If you didn't use a password, just skip this step.

25) You can now use your coins as you wish. I recommend going to the Send tab and send ALLL your Bitcoin Cash to a new wallet you control.

Note: Make sure to use a low fee since a high fee is not necessary for Bitcoin Cash.


I hope this guide helped you. Feel free to link to this guide to anyone who needs it. :)



Sincerely,
[DarkLord_GMS](https://www.reddit.com/user/DarkLord_GMS/)

**Comment by SilverstrandBC** [comment]
Success...  thank you very much DarkLord_GMS.

**Comment by fyookball** [comment]
thx @DarkLordGMS  very much.  I will add this to #41.

**Comment by DarkLordGMS** [comment]
Sure! I'm glad I was able to help out the community. This is what I like the most. :)

**Comment by isajudeh** [comment]
@DarkLordGMS  man I really would like to say thaaaaaaaaaaaaaaaaaaaaaaaaaaank you ... 
I have another problem if you allow to me I sent etherum classic by mistake to wrong address is there any possibility to get it back
