### ISSUE TITLE
Add a button to set the fee to the minimum

### ISSUE THREAD

**Issue by MohamedKiouaz** [fyookball/electrum#178]
Is it possible to add a button to set the fee to the minimum ? This would be really useful since the blocks are empty for now.

**Comment by fyookball** [comment]
Minimum depends on miner policy and since that could change, we would have to keep up with policy, which would burden the maintanence of the wallet.  Actually current policy is that some tx are accepted in each block with 0 fee, so put 0 :)   Right now I suggest sliding the slider to the minimum if you want to use a non-zero min fee.
