### ISSUE TITLE
How to recover lost/misdirected BTC?

### ISSUE THREAD

**Issue by Dbdb368** [fyookball/electrum#378]
I was trying to send BTC from my  electrum wallet to my electron cash wallet as BCH, via shapeshift.
I did it wrong however, i just literally took the electrum address for the refund address and the electron cash address as the destination address
I did not realize I was supposed to use the new address that shapeshift created to send the BTC to.
so electrum wallet shows that transaction as verified. but electron cash wallet is not showing any additions
how do i recover this btc?

**Comment by TitaniBitDAVO** [comment]
I'm kind of in same spot over 5 days now. I sent BTC from bitter to Electron Cash, trans ID confirmed but no bitcoin in my electron cash wallet, can anyone help me? I changed server to electrum-abc.cryptolayer.net

I'm not sure if I'm doing something wrong but still no bitcoin

**Comment by TrustyJAID** [comment]
To add to @Dbdb368 The electrum and electron cash wallets have the same private key. So Sending btc from Electrum to Electron cash should have resulted in sending BTC to itself in Electrum. I suspect it has something to do with Electrum not knowing it has this specific Public Address but otherwise not 100% what went wrong here.

**Comment by ryankemper** [comment]
@Dbdb368 Did you create a new electron cash wallet first, or did you use the same priv key as your BTC (electrum) wallet?

If it's the first, you need to import your electron cash seed into electrum.

If it's the second, your BTC should have been sent right back to the same wallet, and should be there

**Comment by ryankemper** [comment]
@TitaniBitDAVO You didn't provide a lot of info, perhaps supply the txid? Are you sure you sent to your electron cash wallet, and that the BTC transaction made it into a block (has >= 1 confirmation)?

**Comment by TrustyJAID** [comment]
I have solved @Dbdb368 issue by extracting the private key from electron cash and importing it into electrum.
Steps to fix:
In Electron Cash:
- Wallet -> private keys -> export
- find the associated public address and private key
- open Electrum
- File -> New/Restore
- Enter new wallet name and select next
- select Standard wallet
- select Use public or private keys
- Paste the private key from electron cash in the box and select next

I suspect it is because for some reason electron cash generated a new address that electrum hadn't seen despite sharing the same private keys.

**Comment by kyuupichan** [comment]
They have different derivation paths.  Extract the private key and import into a new Electrum wallet as @TrustyJAID explains.
