### ISSUE TITLE
electroncash update from 2.9.2 to 3 need help

### ISSUE THREAD

**Issue by dutchdragon3** [fyookball/electrum#382]
here is the problem  i had electorn chas 2.9.2 i saw that he would not connect to the server so i thought i need to update perhaps so i downloaded the 3.0 version but now when i try to open me wallet it said Failed to execute script electron-cash how can i fix this :(

**Comment by KingParanha** [comment]
This is a major problem ive been having but ive already made a similar post but no one seems to be helping out anymore, its really stupid how they stopped network compatibility without tellong ppl.

**Comment by bcutter** [comment]
Same here. Updated from 2.9.3 to 3.1. When opening old version wallet I was asked if I´d like to convert the wallet to the new format. After yes I get "Failed to execute script electron-cash" error and application is closing. Same behaviour now on every clean start of the application. WHAT THE??? Do we need to create new wallets? **Why there´s no support, no one just telling "it´s because of this, simply do that or that"???**

**Comment by KingParanha** [comment]
Check out #375

**Comment by KingParanha** [comment]
It worked for me, so just give it a go.

**Comment by bcutter** [comment]
So I should enter my seed - just to remind us: the MOST IMPORTANT secret - on a web page? Bad idea, isn´t it? I´ll better start from scratch, wallet didn´t contain anything.

**Comment by fyookball** [comment]
Best to recreate from seed (create new wallet)

**Comment by fyookball** [comment]
we also dont support 2fa, see #41

**Comment by bcutter** [comment]
Beginner´s question: how to do so, if Electron Cash always starts with the existing wallet ("installation assistant")?

**Comment by KingParanha** [comment]
I feel the best option if you really are at your last straw and u have no more options left, using the recovery tool website is the best option because thats ht eonly thing that properly worked for me without any problems.
