### ISSUE TITLE
ElectronCash-3.1.2-PORTABLE for Windows can't show history rates

### ISSUE THREAD

**Issue by LightSunChen** [fyookball/electrum#506]
As title said,  it can't show history rates even the option is ticked.

**Comment by marceloneil** [comment]
History rates are currently unavailable, but will be in the next release. Sorry for the confusion!

A temporary solution in order to restore basic fiat features is to go to your config file (`%appdata%/Electron Cash/config`, or something like that) and remove the line `"history_rates": true`. Enabling "Show history rates" will break it again. It sucks, I know :/
