### ISSUE TITLE
CashAddr crashing android app

### ISSUE THREAD

**Issue by cocoaloco** [fyookball/electrum#556]
On my android 7.0 phone, I turned off the cashaddr format and noticed the address on the 'receive' tab was still a CashAddr address. I clicked 'new' to try and hopefully generate a new legacy address, then the app crashes completely.

**Comment by imaginaryusername** [comment]
Tested and can confirm this bug.

**Comment by marceloneil** [comment]
Can you try the new android version?

**Comment by imaginaryusername** [comment]
3.1.5 still carries the problem (hitting new after format change and before app restart results in a crash). In fact the "new" button in Receive seems to result in crashes in general... no longer sure it has anything to do with Cashaddr.

**Comment by cocoaloco** [comment]
Ye still crashing for me as well

**Comment by cocoaloco** [comment]
Just tested on the new version (3.1.6) still not fixed

**Comment by rt121212121** [comment]
Jonald's policy is to close bugs in the android app as they won't be fixed given we are focusing on the new app which is pending from Marcel.  I've tagged this as backlogged so in the unlikely event someone does go into a burst of bug fixing, despite this issue being open since March, it can be filtered out and found.
