### ISSUE TITLE
Payment protocol links do not work, 3.1.5

### ISSUE THREAD

**Issue by Simplexletalis** [fyookball/electrum#581]
Receive the error:

Invalid bitcoincash URI:
name 'threading' is not defined.

This is on the latest windows build. release 3.0 worked fine.

**Comment by fyookball** [comment]
how to recreate?

**Comment by kyuupichan** [comment]
A sample link would be nice...

**Comment by Simplexletalis** [comment]
This is what I was trying:

bitcoincash:?r=https://bitpay.com/i/4wpPfsrQWPueRGDZxTjRQR

I used the old compiled release of 3.0 to complete the transaction.

**Comment by kyuupichan** [comment]
OK I've fixed the threading import issue in git head.  I now get an error about the server; I think it's misleading and because the payment request has expired.  

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bitpay.com/i/4wpPfsrQWPueRGDZxTjRQR

Is the exception that happens which isn't very informative.  If you have a non-expired payment request it would be great

**Comment by kyuupichan** [comment]
I've pushed something that now gives a sensible message.  Whether it does for all cases I have no idea.

**Comment by imaginaryusername** [comment]
I tried paying a Bitpay invoice and got: 

`pay_script() takes 2 positional arguments but 3 was given` popup, the tx was broadcasted anyway - on the invoice page it returned 

`This invoice received a payment from a wallet that does not support payment protocol`

I'm not sure what was wrong, currently getting Bitpay to either confirm payment or refund me.

**Comment by jhaand** [comment]
When will 3.1.6 become available in the Google Play Store? 

I needed to download the APK separately in order to use BIP70 on Android.
