### ISSUE TITLE
Your fee is too high.  Max is 50 sat/byte.

### ISSUE THREAD

**Issue by vrobolab** [fyookball/electrum#675]
What if I want to set higher fee for faster confirmation?

Example: https://i.imgur.com/7cgMEjK.png

**Comment by vrobolab** [comment]
Several transactions with recommended fee about 0.00000226 took more than 10 minutes. Is that normal for Bitcoin Cash?
I thought it should be faster than Bitcoin.

**Comment by cyio** [comment]
maybe EDA(Emergency Difficulty Adjustment) caused? 1 minutes or 30 minutes a block
The fee is OK, and you have to wait it.

**Comment by rt121212121** [comment]
The general solution to this is that we implement instead of a end of the road notification dialog "Your fee is too high" we instead show a confirmation dialog and let them proceed with as high a fee as they want, and we make the 50 also configurable.  I'd also probably throw in a settings option to enable the change from notify to confirm, etc etc.  Needs some design and thought.

**Comment by marceloneil** [comment]
This also applies to the CLI, I don't know how well prompts work there

**Comment by hegjon** [comment]
> What if I want to set higher fee for faster confirmation?

1 sat/byte fee will work in 99.999% of the transactions, 50 sat/byte is not a use-case today.

**Comment by fyookball** [comment]
"What if I want to set higher fee for faster confirmation?"

You don't need higher fee for faster confirmation.
