### ISSUE TITLE
Where are releases?

### ISSUE THREAD

**Issue by rstormsf** [fyookball/electrum#68]
why the website releases don't match github releases? 
http://www.electroncash.org/

Also for latest versions we don't even know what are release notes.
Since it's financial application, we would like to have more transparency on what is included in the binaries.

**Comment by fyookball** [comment]
I will add a tag for 2.9.2.  You are right i should have redone release notes.

2.9.2 is based off https://github.com/fyookball/electrum/commit/189e94a959710195b19dc80c29dfe84b4f579957

This includes:

Download headers from bitcoincash.com rather than electrum.org
Fixes offline signing
Fixes certain cases of "error 16"
Fixes basic multisig
Fixes basic tx trezor support
Add fx rate for Bitcoin Cash
Pull upstream 2.9.2 changes from Electrum
Include Android in version 2.9.2
