### ISSUE TITLE
Segfault in QT Widgets library on Linux

### ISSUE THREAD

**Issue by JosiahGoeman** [fyookball/electrum#685]
I just used Electron Cash to import my private keys from an old multibit wallet.  This is the first time I've tried to access them post-fork.  It seems to run fine for about 7 seconds, during which I can navigate different tabs, open menus, etc., then crashes.  It does _not_ crash when creating a new, empty wallet.

Attached is the output of running python through gdb, launching Electron Cash, opening the wallet with imported keys, and simply waiting for it to crash.
[gdb_out.txt](https://github.com/fyookball/electrum/files/2009876/gdb_out.txt)

I'm running Linux Mint 18.3 with the x86_64 Linux 4.13.0-41-generic kernel.

**Comment by rt121212121** [comment]
Unfortunately, there's not enough information here to work out why it is crashing.  In order for us to be able to do anything with this, either you need to provide a wallet that exhibits the same problems, or more debugging information.

It's been years since I've debugged Python code with gdb, but [this might be a start](https://wiki.python.org/moin/DebuggingWithGdb) or [this might be a start](https://devguide.python.org/gdb/) for getting the Python stack traces for the cpython frames in the C stacktraces.

**Comment by rt121212121** [comment]
Closing due to lack of information.  Please get back to us if you can do what I suggested.

**Comment by marceloneil** [comment]
This is really odd. I don't really know how to make sense of the gdb output, but I would suggest upgrading pyqt, qt, python, etc.
