### ISSUE TITLE
3.2 on Fedora 28 - Amount shows 'e' instead of number, balance wrong

### ISSUE THREAD

**Issue by sajrajs** [fyookball/electrum#747]
Just upgraded Fedora to 28 and it did EC to 3.2 too.
I can not see the amounts and balance correctly since ... Amount says +e,78946 and balance is a number but wrong value (definitely different value there)
![image](https://user-images.githubusercontent.com/40474207/41742121-58476d14-759d-11e8-9860-e2e6c901c19e.png)

Tried all the settings. 3.2 has this issue on Fedora 27 too. 
thanks a bunch for looking into this!

**Comment by rt121212121** [comment]
This is a Linux decimal bug, where we have to work around it.  I think #684 was related to this, and it may have been fixed there already by @marceloneil.  We'd only ever know if you tested it locally with the latest code.  In any case, just to be sure because this Linux flakiness has been reported three times by different people, I've ported the latest Electrum code across for this formatting in 93ceeab.

Reopen it if you have the same problem after the next release, or in the latest from github, if you can try it out.  But it's expected to be fixed, and not reproducible.

**Comment by sajrajs** [comment]
Thanks a bunch sir for great support ... i searched through known issue but could not find #684.
Will test in next release.
