### ISSUE TITLE
trezor: sign_tx() got an unexpected keyword argument 'locktime'

### ISSUE THREAD

**Issue by molecular** [fyookball/electrum#85]
segregating this from #63 so #63 can be closed to reduce potential for confusion.

from kyuupi:

You need to remove the locktime= from the trezor plugin
electrum keeps adding it back and breaking stuff. line 242 of plugin.py i think

**Comment by molecular** [comment]
hm, I have the locktime in trezor/plugin.py:242:

    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]

but I don't get the error. 

How can I reproduce this?

**Comment by juriise** [comment]
I have python-trezor package 0.6.10-1 which I believe is the latest. (but I get the other message: Assignment not allowed (no field "amount" in protocol message object). )

**Comment by molecular** [comment]
@juriise 0.6.10 is very old. There's a v0.7.16, but even that will be too old.

I think you need to use master branch from https://github.com/trezor/python-trezor

**Comment by molecular** [comment]
I dug in and found that the lock_time argument to sign_tx() function in python-trezor got added 4 months ago. It's in newest version v0.7.16.

So it shouldn't occur in python-trezor v0.07.16 and I think this is a "wontfix" issue for ElectronCash because it presumably works fine with newest python-trezor.

**Comment by BCREAM** [comment]
The only trezor stuff I can find on my computer is that which is in the Electron-Cash-2.9.2 folder that I downloaded from electroncash.org. However, that does not make much sense because I can use my Trezor with the Electrum Wallet that comes with TAILS. So there has to be some Trezor files on my computer that for some reason I cannot find.

Are you saying I need to update one of the files that comes in the Electorn Cash folder? Or are there some Trezor files that comes with TAILS that I need to somehow find and update? And if the latter, do you have any idea as to how to do that?

Thanks.

**Comment by jhoenicke** [comment]
Usually the trick is `sudo pip2 uninstall  trezor` until it cannot find anything to uninstall and then `sudo pip2 install trezor`.  Haven't tried on tails.

**Comment by juriise** [comment]
This was it. I removed all three trezor related packages from the ubuntu packcage system, and the pip uninstall and install commands above. Signing is now ok for me.

**Comment by BCREAM** [comment]
Unfortunately that command does not work for me. I am a pretty big noob when it comes to linux and the command line, but I do not trust Windows or Mac.

When I try the command in tails I get this:

amnesia@amnesia:~$ sudo pip2 uninstall trezor
[sudo] password for amnesia: 
sudo: pip2: command not found

**Comment by jhoenicke** [comment]
@BCREAM it may also be called pip.

**Comment by BCREAM** [comment]
:'(


amnesia@amnesia:~$ sudo pip2 uninstall trezor

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for amnesia: 
sudo: pip2: command not found
amnesia@amnesia:~$ sudo pip uninstall trezor
[sudo] password for amnesia: 
sudo: pip: command not found
amnesia@amnesia:~$ sudo pip1 uninstall trezor
[sudo] password for amnesia: 
sudo: pip1: command not found
amnesia@amnesia:~$ sudo pip3 uninstall trezor
[sudo] password for amnesia: 
sudo: pip3: command not found
amnesia@amnesia:~$ sudo pip4 uninstall trezor
[sudo] password for amnesia: 
sudo: pip4: command not found

**Comment by fyookball** [comment]
can this be closed

**Comment by molecular** [comment]
Discussion is now about how to upgrade python-trezor in peoples systems (which is ok to discuss). There has been 1 report that python-trezor upgrade helped against the specific issue and 0 reports that it still occurs despite an upgrade.

I'd say it can be closed.

**Comment by molecular** [comment]
@bcream if you're on a debian-based system

     #> sudo apt-get install python-pip

on other systems (like archlinux) the package might be called **python2-pip**.

Use your local package manager to search for and install pip.

If installing pip fails, you can also look in /lib/python2.7/site-packages or /usr/lib/... /usr/local/lib/... and just delete any python-trezor* folder you find.

**Comment by molecular** [comment]
@bcream 

The only trezor stuff I can find on my computer is that which is in the Electron-Cash-2.9.2 folder that I downloaded from electroncash.org.

What exactly did you download? I'd like to check wether or not and if so, which python-trezor library files are included.

**Comment by BCREAM** [comment]
@molecular 

In the Electrum-2.9.2 folder I see a trezor folder withtrezor.py, qt.py, plugin.pu, client.py and a couple others.

When I try to install pip

amnesia@amnesia:~$ sudo apt-get install python-pip
[sudo] password for amnesia: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pip



^get the same thing with python2-pip



Tails 3.1 is supposed to come out today, and hopefully they have updated the trezorlib so that I dont have to stay on the struggle bus and learn how to navigate the command line. So far all I really know is cd, ls, and ./, and I just learned how to navigate backwards to the root directory (cd ..).

I have found the trezorlib using your command

/usr/lib/python2.7/dist-packages/trezorlib

However I can not figure out how to uninstall it and install the new stuff. Its probably pretty easy but it'll take me a few hours to figure it out.

cp is supposed to copy, and I tried something like ethis,

sudo cp -a /home/amnesia/Desktop/python-trezor-master/.  /usr/lib/python2.7/dist-packages/trezorlib

but that broke the fee estimator and still gives the bug. :(

If Tails doesn't update then I guess I'll put the hours in of learning this madness

**Comment by jhoenicke** [comment]
You need at least python-trezor version 0.7.13 (which added `lock_time`).   I fear that the latest version in debian is still 0.7.6 and tails is based on debian.

> In the Electrum-2.9.2 folder I see a trezor folder withtrezor.py, qt.py, plugin.pu, client.py and a couple others.

That ist not trezorlib but the plugin that connects to trezorlib.  

> I have found the trezorlib using your command
> /usr/lib/python2.7/dist-packages/trezorlib

You can use `sudo apt remove python-trezor` to remove the old version of python-trezor distributed with tails. Not sure if it works, though, since tails is supposed to be read-only. 

You can try to install manually:

    git clone https://github.com/trezor/python-trezor
    cd python-trezor
    sudo python setup.py install

or to install in user directory use as last command

    python setup.py install --user

**Comment by BCREAM** [comment]
@molecular @jhoenicke 

Tails 3.1 unfortunately did not upgrade it.


first python-trezor folder I find when searching

/usr/share/doc/python-trezor


second python-trezor folder 

/lib/live/mount/rootfs/filesystem.squashfs/usr/share/doc/python-trezor



then the first python-trezor file I see is 

/usr/share/lintian/overrides/python-trezor


the second is 

/lib/live/mount/rootfs/filesystem.squashfs/usr/share/lintian/overrides/python-trezor




There is no python-trezor in /usr/lib/python2.7/dist-packages/trezorlib

What I see in there is

ckd_public.py  mapping.py        tools.py             transport.py
client.py      messages_pb2.py   transport_bridge.py  transport_udp.py
debuglink.py   protobuf_json.py  transport_hid.py     tx_api.py
__init__.py    qt                transport_pipe.py    types_pb2.py



When I try to install manually, I get to last step:

amnesia@amnesia:~/python-trezor$ sudo python setup.py install
[sudo] password for amnesia: 
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
ImportError: No module named setuptools


I see setup.py after I cd python-trezor:

bash_completion.d  MANIFEST.in       setup.py  tox.ini    USAGE.rst
build_pb.sh        README.rst        tests     trezorctl
COPYING            requirements.txt  tools     trezorlib

So not sure what is happening


I know this is probably asking too much, but is there any way one of you could install Tails onto a spare USB laying around and see how you would go about updating it? I am seriously mentally handicapped when it comes to this stuff haha

**Comment by BCREAM** [comment]
@molecular , @jhoenicke 

I will tip you some bitcoin cash pls halp

**Comment by molecular** [comment]
you need to install setuptools

    #> sudo pip2 install setuptools

but that will probably not be the end of it

tails is not exactly a system suitable for development (which running from source kind of is)

**Comment by jhoenicke** [comment]
I now tried it with tails (after working around UEFI boot issues, finding out that my wifi doesn't work and finding my USB hub to connect wired ethernet, the boot stick and the Trezor at the same time to my laptop).

Not sure if copying trezorlib from python-trezor into the electrum directory works, didn't test this.

What works is if you `sudo apt install python-dev cython libusb-1.0-0-dev libudev-dev git; pip2 install trezor --user` on some trusted computer and then copy the `~/.local/lib/python2.7/site-packages/trezor*` directories to your TOR home directory.  If you trust my installation, you can use 

    curl https://jochen-hoenicke.de/misc/python-trezor-0.7.16.tar.gz | tar -xvzf -

in the home directory in the console.

**Comment by BCREAM** [comment]
@molecular 

amnesia@amnesia:~$ sudo pip2 install setuptools
[sudo] password for amnesia: 
sudo: pip2: command not found


@jhoenicke 

amnesia@amnesia:/home$ curl https://jochen-hoenicke.de/misc/python-trezor-0.7.16.tar.gz | tar -xvzf -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to jochen-hoenicke.de port 443: Connection refused

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now


^^maybe its rejecting me because I'm using Tor? 

Also thank you so much for helping me man. I know what a pain in the ass it can be getting Tails up an running. 

I just realized I've been using your website to monitor the mempools of btc and bcc. I am going to tip you at 1FBjCXcLroP93uEZ4BfKi6Z6rw2PwvnAUJ, unless that is just for btc and not bcc. Let me know sir and thank you again.

**Comment by jhoenicke** [comment]
When I tried it yesterday, it worked under tails, but it may depend on which exit node you get.  Not sure what IP addresses my provider is blocking.  You can also try to download the file with TOR browser and extract it manually (`tar -xvzf <downloaded-file>` in your home directory).

The 1FBj address is okay, I can handle bcc.
