### ISSUE TITLE
making sub-dust outputs and 'insufficient priority'

### ISSUE THREAD

**Issue by markblundeberg** [fyookball/electrum#860]
The following transaction was constructed using a custom code pathway that involved using `wallet.make_unsigned_transaction`. It was provided with only two 546-sat coins to work with, and the first two outputs (op_return, and 546 sat output) were specified. The algorithm ended up adding a third change output to the specified change address, however it can be seen that the output amount is less than dust limit.

As a result, when broadcasted to the electrumx server it fails, with the error 'insufficient priority'.

![screenshot from 2018-09-16 22-13-31](https://user-images.githubusercontent.com/36528214/45852566-437bdb00-bcf5-11e8-89fd-f6183cde4ead.png)

**Comment by cculianu** [comment]
Cool, thanks for adding this.

So my proposed solution for this is:

1. Set dust_limit in wallet.py to back to 546.  It's currently set to 1.  The tx generation code uses dust_limit to determine what dust is left over that should go to the tx fee. 

2. Set a flag that the fee ended up being larger than anticipated due to dust.  This flag can be used by the Qt UI to inform the user of that fact so he/she may elect to abort the transaction and construct another transaction later (either by funding the wallet or selecting different coins if they have them).

So the end result of (1) & (2) above will be that dust outputs will no longer be generated for tx's, and the dust will go to the tx fee.  The user will be informed if that happens so they can then decide what to do or not do.

Anyone reading this: Let me know if you disagree with the above or can think of a better approach.

**Comment by cculianu** [comment]
Just wanted to add this Mark since you mentioned it and perhaps it's worth for me (or anyone) to look into:

> Mark [2:51 AM]
> another weird thing in the screenshot: 416 bytes, 417 sat fee ---> fee calculates to 1.00000000 sat/byte??

**Comment by cculianu** [comment]
Ok, this has been fixed in a recent commit.
