### ISSUE TITLE
error compiling Android Package : Path for p4a.source_dir does not exist

### ISSUE THREAD

**Issue by charleshsu168** [fyookball/electrum#90]
BTW, i also failed to build in electrum master branch. i will report an issue there too

**Comment by charleshsu168** [comment]
![image](https://user-images.githubusercontent.com/5799190/29007685-96ed6d06-7abd-11e7-9972-83f365125fe7.png)

**Comment by fyookball** [comment]
i usually point that to home/ubuntu/downloads/python-for-android-master  which contains the
pythonforandroid unzipped folder.  i also customize the pythonutils.java file to fix some problems.  see here:  https://github.com/fyookball/electrum/tree/android2.8.2/contrib/jonald

**Comment by verretor** [comment]
I think the problem comes from this commit. 
[https://github.com/fyookball/electrum/commit/dea5b6d62b6079e5eead7fb65baab9ac95a29a82](url)

gui/kivy/tools/buildozer.spec line 123 was:
`android.p4a_dir = /opt/python-for-android`

And now:
`p4a.source_dir = /home/ubuntu/Downloads/python-for-android-master`

Not everyone has a user named "ubuntu".

**Comment by fyookball** [comment]
@verretor  good catch.  i didnt think many people would be interested in building their own binaries.  I changed this because this is how I build them.  Many default settings simply didn't work for me.  Indeed, try changing it back to the default.  I encountered missing libpythonXXX.so on runtime, which is why i did customizations with the source path.
